        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:49 2014
        MODULE AXISUPDATE__genmod
          INTERFACE 
            SUBROUTINE AXISUPDATE(RAUX,MATR,RCONV)
              REAL(KIND=8), INTENT(IN) :: RAUX(3,3)
              REAL(KIND=8), INTENT(IN) :: MATR(3,3)
              REAL(KIND=8), INTENT(OUT) :: RCONV(3,3)
            END SUBROUTINE AXISUPDATE
          END INTERFACE 
        END MODULE AXISUPDATE__genmod
