        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:49 2014
        MODULE DEFGRAD3D__genmod
          INTERFACE 
            SUBROUTINE DEFGRAD3D(NNODES,NDOF,DNDC,DNDE,DNDZ,JACINV,     &
     &COORDS,DISP,MATF)
              INTEGER(KIND=4), INTENT(IN) :: NDOF
              INTEGER(KIND=4), INTENT(IN) :: NNODES
              REAL(KIND=8), INTENT(IN) :: DNDC(NNODES)
              REAL(KIND=8), INTENT(IN) :: DNDE(NNODES)
              REAL(KIND=8), INTENT(IN) :: DNDZ(NNODES)
              REAL(KIND=8), INTENT(IN) :: JACINV(NDOF,NDOF)
              REAL(KIND=8), INTENT(IN) :: COORDS(NNODES,NDOF)
              REAL(KIND=8), INTENT(IN) :: DISP(NDOF*NNODES,1)
              REAL(KIND=8), INTENT(OUT) :: MATF(3,3)
            END SUBROUTINE DEFGRAD3D
          END INTERFACE 
        END MODULE DEFGRAD3D__genmod
