        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:53 2014
        MODULE ELHEX27_PROJVOL__genmod
          INTERFACE 
            SUBROUTINE ELHEX27_PROJVOL(NEL,KE,EL_DDISP,FINTE,INC)
              USE MOD_VARIABLES
              INTEGER(KIND=4), INTENT(IN) :: NEL
              REAL(KIND=8), INTENT(OUT) :: KE(81,81)
              REAL(KIND=8), INTENT(IN) :: EL_DDISP((P+1)*(Q+1)*(W+1)*NDS&
     &,1)
              REAL(KIND=8), INTENT(OUT) :: FINTE(81,1)
              INTEGER(KIND=4), INTENT(IN) :: INC
            END SUBROUTINE ELHEX27_PROJVOL
          END INTERFACE 
        END MODULE ELHEX27_PROJVOL__genmod
