        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:47 2014
        MODULE FDETERM__genmod
          INTERFACE 
            SUBROUTINE FDETERM(AMATR,DETER)
              REAL(KIND=8), INTENT(IN) :: AMATR(3,3)
              REAL(KIND=8), INTENT(OUT) :: DETER
            END SUBROUTINE FDETERM
          END INTERFACE 
        END MODULE FDETERM__genmod
