        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:54 2014
        MODULE GIDRES__genmod
          INTERFACE 
            SUBROUTINE GIDRES(INC)
              INTEGER(KIND=4), INTENT(IN) :: INC
            END SUBROUTINE GIDRES
          END INTERFACE 
        END MODULE GIDRES__genmod
