        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:46 2014
        MODULE LOCAL_AXIS__genmod
          INTERFACE 
            SUBROUTINE LOCAL_AXIS(NDS,JAC,RCONV)
              INTEGER(KIND=4), INTENT(IN) :: NDS
              REAL(KIND=8), INTENT(IN) :: JAC(NDS,NDS)
              REAL(KIND=8), INTENT(OUT) :: RCONV(NDS,NDS)
            END SUBROUTINE LOCAL_AXIS
          END INTERFACE 
        END MODULE LOCAL_AXIS__genmod
