        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:48 2014
        MODULE MATISOHARDENING__genmod
          INTERFACE 
            SUBROUTINE MATISOHARDENING(NPROPS,PROPS,IPROPS,SYIELD,H)
              INTEGER(KIND=4), INTENT(IN) :: NPROPS
              REAL(KIND=8), INTENT(IN) :: PROPS(NPROPS)
              INTEGER(KIND=4), INTENT(IN) :: IPROPS
              REAL(KIND=8), INTENT(IN) :: SYIELD
              REAL(KIND=8), INTENT(OUT) :: H
            END SUBROUTINE MATISOHARDENING
          END INTERFACE 
        END MODULE MATISOHARDENING__genmod
