        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 18 10:22:37 2014
        MODULE MATPLASTIC3D__genmod
          INTERFACE 
            SUBROUTINE MATPLASTIC3D(IPROPS,NODEDOF,NNODES,PROPS,B,BLINES&
     &,DDISP,STRESS,STRAIN,DSTRAIN,DSTRESS,HARD,MATD)
              INTEGER(KIND=4), INTENT(IN) :: BLINES
              INTEGER(KIND=4), INTENT(IN) :: NNODES
              INTEGER(KIND=4), INTENT(IN) :: NODEDOF
              INTEGER(KIND=4), INTENT(IN) :: IPROPS
              REAL(KIND=8), INTENT(IN) :: PROPS(IPROPS)
              REAL(KIND=8), INTENT(IN) :: B(BLINES,NODEDOF*NNODES)
              REAL(KIND=8), INTENT(IN) :: DDISP(NODEDOF*NNODES,1)
              REAL(KIND=8), INTENT(INOUT) :: STRESS(1,1,6)
              REAL(KIND=8), INTENT(INOUT) :: STRAIN(1,1,6)
              REAL(KIND=8), INTENT(INOUT) :: DSTRAIN(1,1,6)
              REAL(KIND=8), INTENT(INOUT) :: DSTRESS(1,1,6)
              REAL(KIND=8), INTENT(INOUT) :: HARD(1,1)
              REAL(KIND=8), INTENT(INOUT) :: MATD(6,6)
            END SUBROUTINE MATPLASTIC3D
          END INTERFACE 
        END MODULE MATPLASTIC3D__genmod
