        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:52 2014
        MODULE READINFILE__genmod
          INTERFACE 
            SUBROUTINE READINFILE(FILENAME)
              CHARACTER(LEN=256), INTENT(IN) :: FILENAME
            END SUBROUTINE READINFILE
          END INTERFACE 
        END MODULE READINFILE__genmod
