        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:46 2014
        MODULE TRANSFORMATIONMAT3D__genmod
          INTERFACE 
            SUBROUTINE TRANSFORMATIONMAT3D(MATIN,MATTRANS)
              REAL(KIND=8), INTENT(IN) :: MATIN(3,3)
              REAL(KIND=8), INTENT(OUT) :: MATTRANS(6,6)
            END SUBROUTINE TRANSFORMATIONMAT3D
          END INTERFACE 
        END MODULE TRANSFORMATIONMAT3D__genmod
