        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 14 08:53:46 2014
        MODULE VONMISESSTRESS__genmod
          INTERFACE 
            SUBROUTINE VONMISESSTRESS(STRESS,SDIM,SVM)
              INTEGER(KIND=4), INTENT(IN) :: SDIM
              REAL(KIND=8) :: STRESS(SDIM,1)
              REAL(KIND=8), INTENT(OUT) :: SVM
            END SUBROUTINE VONMISESSTRESS
          END INTERFACE 
        END MODULE VONMISESSTRESS__genmod
