        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:31 2014
        MODULE AXISUPDATE2D__genmod
          INTERFACE 
            SUBROUTINE AXISUPDATE2D(RAUX,MATR,RCONV)
              REAL(KIND=8), INTENT(IN) :: RAUX(2,2)
              REAL(KIND=8), INTENT(IN) :: MATR(3,3)
              REAL(KIND=8), INTENT(OUT) :: RCONV(2,2)
            END SUBROUTINE AXISUPDATE2D
          END INTERFACE 
        END MODULE AXISUPDATE2D__genmod
