        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:32 2014
        MODULE BSPLINEBASISANDDERIV2__genmod
          INTERFACE 
            SUBROUTINE BSPLINEBASISANDDERIV2(NCP,P,U,U_KNOT,N,DNDXI,    &
     &DN2DXI2,USPAN)
              INTEGER(KIND=4), INTENT(IN) :: P
              INTEGER(KIND=4), INTENT(IN) :: NCP
              REAL(KIND=8), INTENT(IN) :: U
              REAL(KIND=8), INTENT(IN) :: U_KNOT(NCP+P+1)
              REAL(KIND=8) :: N(NCP)
              REAL(KIND=8) :: DNDXI(NCP)
              REAL(KIND=8) :: DN2DXI2(NCP)
              INTEGER(KIND=4), INTENT(OUT) :: USPAN
            END SUBROUTINE BSPLINEBASISANDDERIV2
          END INTERFACE 
        END MODULE BSPLINEBASISANDDERIV2__genmod
