        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 15:26:24 2014
        MODULE ELIMINATEREAC__genmod
          INTERFACE 
            SUBROUTINE ELIMINATEREAC(ILM)
              INTEGER(KIND=4), INTENT(IN) :: ILM
            END SUBROUTINE ELIMINATEREAC
          END INTERFACE 
        END MODULE ELIMINATEREAC__genmod
