        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:25 2014
        MODULE GEN_IEN_INN__genmod
          INTERFACE 
            SUBROUTINE GEN_IEN_INN
            END SUBROUTINE GEN_IEN_INN
          END INTERFACE 
        END MODULE GEN_IEN_INN__genmod
