        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:13 2014
        MODULE GPTS_CONTACT__genmod
          INTERFACE 
            SUBROUTINE GPTS_CONTACT(ITER,INC,ISTEP)
              USE MOD_VARIABLES
              INTEGER(KIND=4), INTENT(IN) :: ITER
              INTEGER(KIND=4), INTENT(IN) :: INC
              INTEGER(KIND=4), INTENT(IN) :: ISTEP
            END SUBROUTINE GPTS_CONTACT
          END INTERFACE 
        END MODULE GPTS_CONTACT__genmod
