        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:31 2014
        MODULE MATLINEARELASTICDP__genmod
          INTERFACE 
            SUBROUTINE MATLINEARELASTICDP(E,VE,MATD)
              REAL(KIND=8), INTENT(IN) :: E
              REAL(KIND=8), INTENT(IN) :: VE
              REAL(KIND=8), INTENT(OUT) :: MATD(3,3)
            END SUBROUTINE MATLINEARELASTICDP
          END INTERFACE 
        END MODULE MATLINEARELASTICDP__genmod
