        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 16:10:25 2014
        MODULE MATLABIN__genmod
          INTERFACE 
            SUBROUTINE MATLABIN
            END SUBROUTINE MATLABIN
          END INTERFACE 
        END MODULE MATLABIN__genmod
