        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 16:10:25 2014
        MODULE MATLABOUT__genmod
          INTERFACE 
            SUBROUTINE MATLABOUT
            END SUBROUTINE MATLABOUT
          END INTERFACE 
        END MODULE MATLABOUT__genmod
