        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:14 2014
        MODULE MPALLOC__genmod
          INTERFACE 
            SUBROUTINE MPALLOC(IPTCH)
              INTEGER(KIND=4), INTENT(IN) :: IPTCH
            END SUBROUTINE MPALLOC
          END INTERFACE 
        END MODULE MPALLOC__genmod
