        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:14 2014
        MODULE MPDALLOC__genmod
          INTERFACE 
            SUBROUTINE MPDALLOC(IPTCH)
              INTEGER(KIND=4), INTENT(IN) :: IPTCH
            END SUBROUTINE MPDALLOC
          END INTERFACE 
        END MODULE MPDALLOC__genmod
