        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:31 2014
        MODULE POLARDECOMP2D__genmod
          INTERFACE 
            SUBROUTINE POLARDECOMP2D(NDOF,MATF,MATR)
              INTEGER(KIND=4), INTENT(IN) :: NDOF
              REAL(KIND=8), INTENT(IN) :: MATF(NDOF,NDOF)
              REAL(KIND=8), INTENT(OUT) :: MATR(NDOF,NDOF)
            END SUBROUTINE POLARDECOMP2D
          END INTERFACE 
        END MODULE POLARDECOMP2D__genmod
