        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:25 2014
        MODULE PTS_COLLOCATIONPOINTS__genmod
          INTERFACE 
            SUBROUTINE PTS_COLLOCATIONPOINTS
            END SUBROUTINE PTS_COLLOCATIONPOINTS
          END INTERFACE 
        END MODULE PTS_COLLOCATIONPOINTS__genmod
