        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:25 2014
        MODULE PTS_SLAVESEGMENT__genmod
          INTERFACE 
            SUBROUTINE PTS_SLAVESEGMENT(ITER,INC,ISTP,IPTCH)
              USE MOD_VARIABLES
              INTEGER(KIND=4) :: ITER
              INTEGER(KIND=4) :: INC
              INTEGER(KIND=4) :: ISTP
              INTEGER(KIND=4) :: IPTCH
            END SUBROUTINE PTS_SLAVESEGMENT
          END INTERFACE 
        END MODULE PTS_SLAVESEGMENT__genmod
