        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:31 2014
        MODULE PTS_SLAVEIEN__genmod
          INTERFACE 
            SUBROUTINE PTS_SLAVEIEN(P,NNODES,NELEMS,NDS,U_KNOT,INN,IEN)
              INTEGER(KIND=4), INTENT(IN) :: NDS
              INTEGER(KIND=4), INTENT(IN) :: NELEMS
              INTEGER(KIND=4), INTENT(IN) :: NNODES
              INTEGER(KIND=4), INTENT(IN) :: P
              REAL(KIND=8), INTENT(IN) :: U_KNOT(NNODES+P+1)
              INTEGER(KIND=4), INTENT(OUT) :: INN(NNODES,NDS)
              INTEGER(KIND=4), INTENT(OUT) :: IEN(NELEMS,P+1)
            END SUBROUTINE PTS_SLAVEIEN
          END INTERFACE 
        END MODULE PTS_SLAVEIEN__genmod
