        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:25 2014
        MODULE READINFILE__genmod
          INTERFACE 
            SUBROUTINE READINFILE(FILENAME)
              CHARACTER(LEN=256), INTENT(IN) :: FILENAME
            END SUBROUTINE READINFILE
          END INTERFACE 
        END MODULE READINFILE__genmod
