        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 14:25:05 2014
        MODULE STPDALLOC__genmod
          INTERFACE 
            SUBROUTINE STPDALLOC(ISTP)
              INTEGER(KIND=4), INTENT(IN) :: ISTP
            END SUBROUTINE STPDALLOC
          END INTERFACE 
        END MODULE STPDALLOC__genmod
