        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:31 2014
        MODULE TRANSFORMATIONMAT2D__genmod
          INTERFACE 
            SUBROUTINE TRANSFORMATIONMAT2D(MATIN,MATTRANS)
              REAL(KIND=8), INTENT(IN) :: MATIN(2,2)
              REAL(KIND=8), INTENT(OUT) :: MATTRANS(3,3)
            END SUBROUTINE TRANSFORMATIONMAT2D
          END INTERFACE 
        END MODULE TRANSFORMATIONMAT2D__genmod
