        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 15:00:50 2014
        MODULE UPDATEPOINTS__genmod
          INTERFACE 
            SUBROUTINE UPDATEPOINTS(NZE,NZEP)
              INTEGER(KIND=4), INTENT(IN) :: NZE
              INTEGER(KIND=4), INTENT(IN) :: NZEP
            END SUBROUTINE UPDATEPOINTS
          END INTERFACE 
        END MODULE UPDATEPOINTS__genmod
