        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 15:24:07 2014
        MODULE ASSEMBLEREDUCED__genmod
          INTERFACE 
            SUBROUTINE ASSEMBLEREDUCED
            END SUBROUTINE ASSEMBLEREDUCED
          END INTERFACE 
        END MODULE ASSEMBLEREDUCED__genmod
