        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:32 2014
        MODULE DEFGRAD2D__genmod
          INTERFACE 
            SUBROUTINE DEFGRAD2D(NNODES,NDOF,DNDC,DNDE,JACINV,COORDS,   &
     &DISP,MATF)
              INTEGER(KIND=4), INTENT(IN) :: NDOF
              INTEGER(KIND=4), INTENT(IN) :: NNODES
              REAL(KIND=8), INTENT(IN) :: DNDC(NNODES)
              REAL(KIND=8), INTENT(IN) :: DNDE(NNODES)
              REAL(KIND=8), INTENT(IN) :: JACINV(NDOF,NDOF)
              REAL(KIND=8), INTENT(IN) :: COORDS(NNODES,NDOF)
              REAL(KIND=8), INTENT(IN) :: DISP(NDOF*NNODES,1)
              REAL(KIND=8), INTENT(OUT) :: MATF(3,3)
            END SUBROUTINE DEFGRAD2D
          END INTERFACE 
        END MODULE DEFGRAD2D__genmod
