        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:25 2014
        MODULE GIDEQMESH__genmod
          INTERFACE 
            SUBROUTINE GIDEQMESH(COORD)
              USE MOD_VARIABLES
              REAL(KIND=8) :: COORD(NCPX*NCPY,NDS)
            END SUBROUTINE GIDEQMESH
          END INTERFACE 
        END MODULE GIDEQMESH__genmod
