        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:14 2014
        MODULE GIDRES__genmod
          INTERFACE 
            SUBROUTINE GIDRES(INC)
              INTEGER(KIND=4), INTENT(IN) :: INC
            END SUBROUTINE GIDRES
          END INTERFACE 
        END MODULE GIDRES__genmod
