        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:25 2014
        MODULE GPTS_INITIALISATION__genmod
          INTERFACE 
            SUBROUTINE GPTS_INITIALISATION
            END SUBROUTINE GPTS_INITIALISATION
          END INTERFACE 
        END MODULE GPTS_INITIALISATION__genmod
