        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 16:10:25 2014
        MODULE ICOHEADER__genmod
          INTERFACE 
            SUBROUTINE ICOHEADER
            END SUBROUTINE ICOHEADER
          END INTERFACE 
        END MODULE ICOHEADER__genmod
