        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 03 16:45:30 2014
        MODULE LOCAL_AXIS_2D__genmod
          INTERFACE 
            SUBROUTINE LOCAL_AXIS_2D(NDS,JAC,RCONV)
              INTEGER(KIND=4), INTENT(IN) :: NDS
              REAL(KIND=8), INTENT(IN) :: JAC(NDS,NDS)
              REAL(KIND=8), INTENT(OUT) :: RCONV(NDS,NDS)
            END SUBROUTINE LOCAL_AXIS_2D
          END INTERFACE 
        END MODULE LOCAL_AXIS_2D__genmod
