        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:14 2014
        MODULE PTS_CONTACTFORCES__genmod
          INTERFACE 
            SUBROUTINE PTS_CONTACTFORCES(ITER,INC)
              USE MOD_VARIABLES
              INTEGER(KIND=4), INTENT(IN) :: ITER
              INTEGER(KIND=4), INTENT(IN) :: INC
            END SUBROUTINE PTS_CONTACTFORCES
          END INTERFACE 
        END MODULE PTS_CONTACTFORCES__genmod
