        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:15 2014
        MODULE PTS_COMPUTEGAPPENAL__genmod
          INTERFACE 
            SUBROUTINE PTS_COMPUTEGAPPENAL(ITER,INC,ISTEP,ILM)
              USE MOD_VARIABLES
              INTEGER(KIND=4), INTENT(IN) :: ITER
              INTEGER(KIND=4), INTENT(IN) :: INC
              INTEGER(KIND=4), INTENT(IN) :: ISTEP
              INTEGER(KIND=4), INTENT(OUT) :: ILM
            END SUBROUTINE PTS_COMPUTEGAPPENAL
          END INTERFACE 
        END MODULE PTS_COMPUTEGAPPENAL__genmod
