        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 10:58:16 2014
        MODULE PTS_COMPUTEGAP__genmod
          INTERFACE 
            SUBROUTINE PTS_COMPUTEGAP(ITER,INC,ISTEP,ILM)
              USE MOD_VARIABLES
              INTEGER(KIND=4), INTENT(IN) :: ITER
              INTEGER(KIND=4), INTENT(IN) :: INC
              INTEGER(KIND=4), INTENT(IN) :: ISTEP
              INTEGER(KIND=4), INTENT(OUT) :: ILM
            END SUBROUTINE PTS_COMPUTEGAP
          END INTERFACE 
        END MODULE PTS_COMPUTEGAP__genmod
