        !COMPILER-GENERATED INTERFACE MODULE: Wed May 28 14:25:05 2014
        MODULE STPALLOC__genmod
          INTERFACE 
            SUBROUTINE STPALLOC(ISTP)
              INTEGER(KIND=4), INTENT(IN) :: ISTP
            END SUBROUTINE STPALLOC
          END INTERFACE 
        END MODULE STPALLOC__genmod
